### ISSUE TITLE
move transports into the library gated behind features

### ISSUE THREAD

**Issue by kloenk** [Gessler-GmbH/smp-rs#2]
I would like to move the transport ways into the library, as I feel like this is always the same, and could be reused (or a new crate that is library). How do you feel about that aproach?
(also is there matrix/irc maybe ideas like this are easier to discuss there first).

**Comment by SZenglein** [comment]
That's a good idea, the serial transport encoding is already in the library, it would only be logical to add some more helpers in that direction.

The transport abstractions in smp-tool are not fleshed out completely and would need some changes like proper Error types and so on, but low-level common code can definitely be added, even though it's fairly trivial for UDP, not sure about Bluetooth.   
One would also have to consider async support, so depending on what you plan a feature for sync-transport and async-transport is needed.


Regarding a chat, we don't have anything public, and frankly I'm not a fan of chat rooms for software projects, because they are not well searchable.  
I'm fine with Github issues (it's not like we are swarmed with issues). I could also enable Github discussions for questions. If you have any other question you must ask personally, feel free to send me an e-mail

**Comment by Kloenk** [comment]
I was planing to just move all transport behind an async trait. Because serial and UDP is also possible via async.
I started a bit on it, but nothing fleshed out enough yet.
